spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/Documents/dev/h2/message-localization
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 256
        batch_fetch_style: dynamic
        query:
          in_clause_parameter_padding: true
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
  data:
    web:
      pageable:
        default-page-size: 20
  messages:
    basename: i18n/messages,i18n/exceptions   # resources 에 messages.properties 파일 위치
logging:
  level:
    org.hibernate.SQL: debug


